[package]
name = "xanadu"
version = "0.2.0"
authors = ["Max Morehead <moreheadmax@gmail.com>"]
edition = "2018"

[dependencies]
shakmaty = "0.16"
chess = "3.1"
rand = "0.7"
arrayvec = "0.5"

[profile.release]
opt-level = 3
debug = true