[package]
name = "xanadu"
version = "0.1.0"
authors = ["Max Morehead <moreheadmax@gmail.com>"]
edition = "2018"

[dependencies]
shakmaty = "0.16"
rand = "0.7"

[profile.release]
opt-level = 3
debug = true